services:
  web:
    build: services/web
    volumes:
      - ./services/web/nginx:/etc/nginx/conf.d
    ports: 
      - 5000:443
    networks:
      - appnet
  api:
    build: services/api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5002:80
      - 5001:443
    networks:
      - appnet
  service_discovery:
    build: services/serviceDiscovery
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports: 
      - 5002:443
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
