services:
  api.app.com:
    build: services/api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports: 
      - 5000:80
    networks:
      - appnet
  web.app.com:
    build: services/web
    volumes:
      - ./services/web/nginx:/etc/nginx/conf.d
    ports: 
      - 5001:80
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
