services:
  web:
    build: services/web
    volumes:
      - ./services/web/nginx:/etc/nginx/conf.d
    ports: 
      - 5000:443
    networks:
      - appnet
  api:
    build: services/api
    environment:
      ASPNETCORE_ENVIRONMENT: Production,
    ports:
      - 5001:80
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
