services:
  web:
    build: services/web
    volumes:
      - ./services/web/nginx/conf.d/:/etc/nginx/conf.d/
      - ./services/web/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 5000:80
    networks:
      - appnet
  api:
    build: services/api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5001:80
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
