services:
  api:
    build: services/api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports: 
      - 5000:80
    networks:
      - appnet
  web:
    build: services/web
    ports: 
      - 5001:80
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
