services:
  web:
    build: services/web
    volumes:
      - ./services/web/config/nginx/:/etc/nginx/
      - ./services/web/config/www/config.js:/data/www/config.js
    ports: 
      - 5000:80
    networks:
      - appnet
  api:
    build: services/api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5001:80
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
