apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-cert
spec:
  commonName: imagehiding.com
  secretName: web-cert
  dnsNames:
    - imagehiding.com
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
spec:
  commonName: api.imagehiding.com
  secretName: api-cert
  dnsNames:
    - api.imagehiding.com
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
