name: Pull merge
description: Programmatically merge branches via a pull request

inputs:
  base:
    description: The base branch
    required: true
  head:
    description: The head branch
    required: true
  title:
    description: The title of the pull request
    required: true
  merge_method:
    description: The merge method
    required: false
    default: merge
  delete_head:
    description: Delete the head branch after merge
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checking out the repository
      uses: actions/github-script@v6
      with:
        script: |
          const pullRequest = await github.rest.pulls.create({
            owner: '${{ github.event.repository.owner.login }}',
            repo: '${{ github.event.repository.name }}',
            base: '${{ inputs.base }}',
            head: '${{ inputs.head }}',
            title: '${{ inputs.title }}',
            body: '',
            commit_message: '${{ inputs.title }}',
          })

          const mergeResult = await github.rest.pulls.merge({
            owner: '${{ github.event.repository.owner.login }}',
            repo: '${{ github.event.repository.name }}',
            pull_number: pullRequest.data.number,
            merge_method: '${{ inputs.merge_method }}'
          })

          console.log(mergeResult.status)

          if ('${{ inputs.delete_head }}' === 'false') {
            return
          }

          const deleteResult = await github.rest.git.deleteRef({
            owner: '${{ github.event.repository.owner.login }}',
            repo: '${{ github.event.repository.name }}',
            ref: 'heads/${{ inputs.head }}',
          })

          console.log(deleteResult.status)
