apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: api
          image: rg.fr-par.scw.cloud/image-data-hiding/api:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '1000m'
              memory: '1Gi'
            limits:
              cpu: '2000m'
              memory: '2Gi'
          ports:
            - containerPort: 80
