apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-cert
spec:
  commonName: imagehiding.com
  secretName: web-cert
  dnsNames:
    - imagehiding.com
    - www.imagehiding.com
  issuerRef:
    kind: _
    name: _
