apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service
resources:
  - namespace.yaml
  - certificate.yaml
  - web/config.yaml
  - web/service.yaml
  - web/deployment.yaml
  - api/service.yaml
  - api/deployment.yaml
  - route.yaml
patches:
  - patch: |
      apiVersion: _
      kind: _
      metadata:
        name: _
      spec:
        automountServiceAccountToken: false
        revisionHistoryLimit: 5
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    target:
      kind: Deployment
