name: Need to run
description: Checks if a job needs to be run
inputs:
  project:
    description: The project to check for
    required: true
outputs:
  random-number:
    description: 'Random number'
    value: ${{ 1 }}
runs:
  using: 'composite'
  steps:
    - name: Set pull request base commit sha
      run: echo "PR_BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
      shell: bash
    - name: Checkout pull request base commit sha
      uses: actions/checkout@v2
      with:
        sha: ${{ env.PR_BASE_SHA }}
    - name: Echo debug information
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        ls -la
        env
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Run script
      env:
        PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
      run: ./check.sh ${{ inputs.project }}
      shell: bash
      working-directory: ${{ github.action_path }}
