name: Need to run
description: Checks if a job needs to be run
inputs:
  project:
    description: The project to check for
    required: true
outputs:
  result:
    description: If the step should be run
    value: ${{ steps.foo.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Run script
      id: foo
      run: ./check.sh ${{ inputs.project }}
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Echo debug information
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: env
      shell: bash
