name: Check if files have changed

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
