name: Run code style fixes

on:
  pull_request:
    branches:
      - main

jobs:
  should_run:
    uses: JensDll/should-run/.github/workflows/main.yaml@dev
    with:
      projects: api web

  api:
    if: fromJSON(needs.should_run.outputs.result).api == 'true'
    runs-on: ubuntu-latest
    needs: should_run
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: env

  web:
    if: fromJSON(needs.should_run.outputs.result).web == 'true'
    runs-on: ubuntu-latest
    needs: should_run
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x.x

      - name: Use node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: web/pnpm-lock.yaml

      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: env

      - name: Install dependencies
        run: pnpm install

      - name: Run code style fixes
        run: pnpm run fix

      - name: Commit changes
        run: |
          git config --show-origin --list
