name: Normalize code style

on:
  pull_request:
    branches:
      - main

jobs:
  needs-to-run:
    uses: ./.github/workflows/needsToRun.yaml
    with:
      projects: api web

  api:
    runs-on: ubuntu-latest
    needs: needs-to-run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Debug information
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          git branch -a
          git remote
          git log --oneline
          echo "$NEEDS_CONTEXT"

  web:
    runs-on: ubuntu-latest
    needs: needs-to-run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Debug information
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          git branch -a
          git remote
          git log --oneline
          echo "$NEEDS_CONTEXT"
