name: Debug Action
on:
  pull_request:
    branches:
      - main
jobs:
  needs-to-run:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.api.outputs.result }}
      web: ${{ steps.web.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - id: api
        uses: ./.github/actions/needs-to-run
        with:
          project: api
      - id: web
        uses: ./.github/actions/needs-to-run
        with:
          project: web
  api:
    runs-on: ubuntu-latest
    needs: needs-to-run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Debug information
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          git branch -a
          git remote
          git log --oneline
          echo "$NEEDS_CONTEXT"
  web:
    runs-on: ubuntu-latest
    needs: needs-to-run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Debug information
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          git branch -a
          git remote
          git log --oneline
          echo "$NEEDS_CONTEXT"
