name: Run code style fixes

on:
  pull_request:
    branches:
      - main

jobs:
  should_run:
    uses: JensDll/should-run/.github/workflows/main.yaml@dev
    with:
      projects: api web

  api:
    if: fromJSON(needs.should_run.outputs.result).api == 'true'
    runs-on: ubuntu-latest
    needs: should_run
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Debug information
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          git branch -a
          git remote
          git log --oneline
          echo "$NEEDS_CONTEXT"

  web:
    if: fromJSON(needs.should_run.outputs.result).web == 'true'
    runs-on: ubuntu-latest
    needs: should_run
    steps:
      - name: Debug information
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          git branch -a
          git remote
          git log --oneline
          echo "$NEEDS_CONTEXT"
