name: Normalize code style

on:
  pull_request:
    branches:
      - main

jobs:
  needs_to_run:
    uses: ./.github/workflows/needsToRun.yaml
    with:
      projects: api web

  api:
    if: fromJSON(needs.needs_to_run.outputs.result).api == 'true'
    runs-on: ubuntu-latest
    needs: needs_to_run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Debug information
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          git branch -a
          git remote
          git log --oneline
          echo "$NEEDS_CONTEXT"

  web:
    if: fromJSON(needs.needs_to_run.outputs.result).web == 'true'
    runs-on: ubuntu-latest
    needs: needs_to_run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Debug information
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          git branch -a
          git remote
          git log --oneline
          echo "$NEEDS_CONTEXT"
