name: Debug Action
on:
  pull_request:
    branches:
      - main
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run my action
        id: needs-to-run
        uses: ./.github/actions/needs-to-run
        with:
          project: api
      - name: Debug information
        env:
          STEP_CONTEXT: ${{ toJSON(steps) }}
        run: |
          git branch -a
          git remote
          git log --oneline
          echo "$STEP_CONTEXT"
