name: Debug Action
on:
  pull_request:
    branches:
      - main
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Run my action
        id: needs-to-run
        uses: ./.github/actions/needs-to-run
        with:
          project: web
      - name: Debug information
        run: |
          git branch -a
          git remote
          git log --oneline
          echo ${{ toJSON(steps) }}
