name: Deployment

on:
  workflow_run:
    workflows:
      - Testing
    types:
      - completed
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: env

  push-to-docker-hub:
    if: github.event.workflow_run.conclusion == 'success'
    environment:
      name: deployment
      url: https://hub.docker.com/repository/docker/jensdll/image-data-hiding
    defaults:
      run:
        shell: bash
        working-directory: deploy/docker
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Setting up Quick Emulator (QEMU)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'linux/arm64,linux/amd64'

      - name: Setting up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Logging in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Building and pushing container images
        run: |
          ./push.sh --provider docker
