name: Formatting

on:
  push:
    branches:
      - '**'

jobs:
  should-run:
    uses: JensDll/should-run/.github/workflows/main.yaml@main
    with:
      projects: services/web services/api

  test-web:
    needs: should-run
    if: fromJSON(needs.should-run.outputs.result)['services/web'] == 'true'
    uses: ./.github/workflows/test-web.yaml

  web:
    needs: test-web
    defaults:
      run:
        shell: bash
        working-directory: services/web
    runs-on: ubuntu-latest
    steps:
      - name: Running code style fixes
        run: pnpm run fix

      - name: Committing changes
        run: |
          if ! git diff --quiet
          then
            git config user.name github-actions
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git pull
            git add --update
            git commit -m "github-actions: fix code style"
            git push
          else
            echo "Nothing to commit!"
          fi

  # api:
  #   if: fromJSON(needs.should-run.outputs.result)['services/api'] == 'true'
  #   needs: should-run
  #   defaults:
  #     run:
  #       shell: bash
  #       working-directory: services/api
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checking out the repository
  #       uses: actions/checkout@v3
