name: Formatting

on:
  push:
    branches:
      - develop

jobs:
  should-run:
    uses: JensDll/should-run/.github/workflows/main.yaml@main
    with:
      projects: services/web services/api

  test-web:
    needs: should-run
    if: fromJSON(needs.should-run.outputs.result)['services/web'] == 'true'
    uses: ./.github/workflows/test-web.yaml

  web:
    needs: test-web
    defaults:
      run:
        shell: bash
        working-directory: services/web
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Using pnpm version 7.x.x
        uses: pnpm/action-setup@v2
        with:
          version: 7.x.x

      - name: Using node version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: services/web/pnpm-lock.yaml

      - name: Installing dependencies
        run: pnpm install

      - name: Running code style fixes
        run: pnpm run fix

      - name: Committing changes
        run: |
          if ! git diff --quiet
          then
            git config user.name github-actions
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git pull
            git add --update
            git commit -m "github-actions: fix code style"
            git push
          else
            echo "Nothing to commit!"
          fi

  test-api:
    needs: should-run
    if: fromJSON(needs.should-run.outputs.result)['services/api'] == 'true'
    uses: ./.github/workflows/test-api.yaml

  api:
    needs: test-api
    defaults:
      run:
        shell: bash
        working-directory: services/api
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3
