name: Formatting

on:
  workflow_run:
    workflows:
      - 'Testing'
    types:
      - 'completed'
    branches:
      - 'develop'

jobs:
  web:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    defaults:
      run:
        shell: bash
        working-directory: services/web
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Using pnpm version 7.x.x
        uses: pnpm/action-setup@v2
        with:
          version: 7.x.x

      - name: Using node version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: services/web/pnpm-lock.yaml

      - name: Installing dependencies
        run: pnpm install

      - name: Running code style fixes
        run: pnpm run fix

      - name: Committing changes
        run: |
          if ! git diff --quiet
          then
            git config user.name github-actions
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git pull
            git add --update
            git commit -m "github-actions: fix code style"
            git push
          else
            echo "Nothing to commit!"
          fi

  api:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    defaults:
      run:
        shell: bash
        working-directory: services/api
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3
