name: Integrate changes into main

on:
  workflow_dispatch:

jobs:
  merge-staging-into-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          ref: staging
