name: Creating pull request onto main

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  create-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Creating pull request
        uses: ./.github/actions/create-pull
        id: create-pull
        with:
          base: main
          head: staging
          title: 'github-actions: merge staging into main'
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
