name: Testing

on:
  pull_request:
    branches:
      - '**'
  push:
    branches-ignore:
      - 'main'
      - 'develop'

jobs:
  should-run:
    uses: JensDll/should-run/.github/workflows/main.yaml@main
    with:
      projects: services/web services/api

  web:
    needs: should-run
    if: fromJSON(needs.should-run.outputs.result)['services/web'] == 'true'
    uses: ./.github/workflows/test-web.yaml

  api:
    needs: should-run
    if: fromJSON(needs.should-run.outputs.result)['services/api'] == 'true'
    uses: ./.github/workflows/test-api.yaml
