name: Running tests

on:
  pull_request:
    branches:
      - staging
jobs:
  should-run:
    uses: JensDll/should-run/.github/workflows/main.yaml@main
    with:
      projects: services/web services/api

  test-web:
    needs: should-run
    if: fromJSON(needs.should-run.outputs.result)['services/web'] == 'true'
    uses: ./.github/workflows/test-web.yaml

  test-api:
    needs: should-run
    if: fromJSON(needs.should-run.outputs.result)['services/api'] == 'true'
    uses: ./.github/workflows/test-api.yaml
