name: Running tests

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  should-run:
    uses: JensDll/should-run/.github/workflows/main.yaml@main
    with:
      projects: services/web services/api

  test-web:
    needs: should-run
    if: fromJSON(needs.should-run.outputs.result)['services/web'] == 'true'
    uses: ./.github/workflows/test-web.yaml

  test-api:
    needs: should-run
    if: fromJSON(needs.should-run.outputs.result)['services/api'] == 'true'
    uses: ./.github/workflows/test-api.yaml

  merge-pull-request:
    if: always() && github.base.ref == 'main'
    needs:
      - test-web
      - test-api
    runs-on: ubuntu-latest
    steps:
      - name: Merging pull request
        uses: ./.github/actions/merge-pull
        with:
          pull_number: ${{ github.event.number }}
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
