apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-cert
spec:
  commonName: imagehiding.dev
  dnsNames:
    - imagehiding.dev
    - www.imagehiding.dev
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
spec:
  commonName: api.imagehiding.dev
  dnsNames:
    - api.imagehiding.dev
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: www-redirect
spec:
  redirectRegex:
    regex: ^https://www.imagehiding.dev(.*)
    replacement: https://imagehiding.dev${1}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web-route
spec:
  routes:
    - match: Host(`imagehiding.dev`) || Host(`www.imagehiding.dev`)
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-route
spec:
  routes:
    - match: Host(`api.imagehiding.dev`)
